config/routes.rb
Citybuilder::Application.routes.draw do

  resources :icons

  resources :surveys

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  

  resources :instances

  resources :expenditures

  resources :categories

  resources :regions

  resources :cities

  resources :models

  root :to => 'pages#index'

end

app/models/instance.rb
class Instance < ActiveRecord::Base
  belongs_to :expenditure
  belongs_to :city
  attr_accessible :amount, :year, :expenditure_id, :city_id
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  # GET /instances
  # GET /instances.json
  def index
    @instances = Instance.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @instances }
    end
  end

  # GET /instances/1
  # GET /instances/1.json
  def show
    @instance = Instance.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @instance }
    end
  end

  # GET /instances/new
  # GET /instances/new.json
  def new
    @instance = Instance.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @instance }
    end
  end

  # GET /instances/1/edit
  def edit
    @instance = Instance.find(params[:id])
  end

  # POST /instances
  # POST /instances.json
  def create
    @instance = Instance.new(params[:instance])

    respond_to do |format|
      if @instance.save
        format.html { redirect_to @instance, notice: 'Instance was successfully created.' }
        format.json { render json: @instance, status: :created, location: @instance }
      else
        format.html { render action: "new" }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /instances/1
  # PUT /instances/1.json
  def update
    @instance = Instance.find(params[:id])

    respond_to do |format|
      if @instance.update_attributes(params[:instance])
        format.html { redirect_to @instance, notice: 'Instance was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @instance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instances/1
  # DELETE /instances/1.json
  def destroy
    @instance = Instance.find(params[:id])
    @instance.destroy

    respond_to do |format|
      format.html { redirect_to instances_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/instances_helper.rb
module InstancesHelper
end

app/views/instances/_form.html.erb
<%= form_for(@instance) do |f| %>
  <% if @instance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instance.errors.count, "error") %> prohibited this instance from being saved:</h2>

      <ul>
      <% @instance.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :expenditure %><br />
    <%= f.text_field :expenditure %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instances/edit.html.erb
<h1>Editing instance</h1>

<%= render 'form' %>

<%= link_to 'Show', @instance %> |
<%= link_to 'Back', instances_path %>

app/views/instances/index.html.erb
<h1>Listing instances</h1>

<table>
  <tr>
    <th>Expenditure</th>
    <th>Amount</th>
    <th>Year</th>
    <th>City</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @instances.each do |instance| %>
  <tr>
    <td><%= instance.expenditure %></td>
    <td><%= instance.amount %></td>
    <td><%= instance.year %></td>
    <td><%= instance.city %></td>
    <td><%= link_to 'Show', instance %></td>
    <td><%= link_to 'Edit', edit_instance_path(instance) %></td>
    <td><%= link_to 'Destroy', instance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Instance', new_instance_path %>

app/views/instances/new.html.erb
<h1>New instance</h1>

<%= render 'form' %>

<%= link_to 'Back', instances_path %>

app/views/instances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Expenditure:</b>
  <%= @instance.expenditure %>
</p>

<p>
  <b>Amount:</b>
  <%= @instance.amount %>
</p>

<p>
  <b>Year:</b>
  <%= @instance.year %>
</p>

<p>
  <b>City:</b>
  <%= @instance.city %>
</p>


<%= link_to 'Edit', edit_instance_path(@instance) %> |
<%= link_to 'Back', instances_path %>