config/routes.rb
Citybuilder::Application.routes.draw do

  resources :icons

  resources :surveys

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users

  

  resources :instances

  resources :expenditures

  resources :categories

  resources :regions

  resources :cities

  resources :models

  root :to => 'pages#index'

end

app/models/icon.rb
class Icon < ActiveRecord::Base
  has_many :categories
  attr_accessible :alt_text, :image, :main_text, :name
end

app/controllers/icons_controller.rb
class IconsController < ApplicationController
  # GET /icons
  # GET /icons.json
  def index
    @icons = Icon.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @icons }
    end
  end

  # GET /icons/1
  # GET /icons/1.json
  def show
    @icon = Icon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @icon }
    end
  end

  # GET /icons/new
  # GET /icons/new.json
  def new
    @icon = Icon.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @icon }
    end
  end

  # GET /icons/1/edit
  def edit
    @icon = Icon.find(params[:id])
  end

  # POST /icons
  # POST /icons.json
  def create
    @icon = Icon.new(params[:icon])

    respond_to do |format|
      if @icon.save
        format.html { redirect_to @icon, notice: 'Icon was successfully created.' }
        format.json { render json: @icon, status: :created, location: @icon }
      else
        format.html { render action: "new" }
        format.json { render json: @icon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /icons/1
  # PUT /icons/1.json
  def update
    @icon = Icon.find(params[:id])

    respond_to do |format|
      if @icon.update_attributes(params[:icon])
        format.html { redirect_to @icon, notice: 'Icon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @icon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /icons/1
  # DELETE /icons/1.json
  def destroy
    @icon = Icon.find(params[:id])
    @icon.destroy

    respond_to do |format|
      format.html { redirect_to icons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/icons_helper.rb
module IconsHelper
end

app/views/icons/_form.html.erb
<%= form_for(@icon) do |f| %>
  <% if @icon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@icon.errors.count, "error") %> prohibited this icon from being saved:</h2>

      <ul>
      <% @icon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :main_text %><br />
    <%= f.text_field :main_text %>
  </div>
  <div class="field">
    <%= f.label :alt_text %><br />
    <%= f.text_field :alt_text %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_area :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/icons/edit.html.erb
<h1>Editing icon</h1>

<%= render 'form' %>

<%= link_to 'Show', @icon %> |
<%= link_to 'Back', icons_path %>

app/views/icons/index.html.erb
<h1>Listing icons</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Main text</th>
    <th>Alt text</th>
    <th>Image</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @icons.each do |icon| %>
  <tr>
    <td><%= icon.name %></td>
    <td><%= icon.main_text %></td>
    <td><%= icon.alt_text %></td>
    <td><%= icon.image %></td>
    <td><%= link_to 'Show', icon %></td>
    <td><%= link_to 'Edit', edit_icon_path(icon) %></td>
    <td><%= link_to 'Destroy', icon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Icon', new_icon_path %>

app/views/icons/new.html.erb
<h1>New icon</h1>

<%= render 'form' %>

<%= link_to 'Back', icons_path %>

app/views/icons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @icon.name %>
</p>

<p>
  <b>Main text:</b>
  <%= @icon.main_text %>
</p>

<p>
  <b>Alt text:</b>
  <%= @icon.alt_text %>
</p>

<p>
  <b>Image:</b>
  <%= @icon.image %>
</p>


<%= link_to 'Edit', edit_icon_path(@icon) %> |
<%= link_to 'Back', icons_path %>